name: "Prepare Deploy"
description: "Bundle action to prepare the build process"
inputs:
  source:
    description: "Source directory"
    required: false
    default: 'source'
  built:
    description: "Previous build directory"
    required: false
    default: 'built'
  git-token:
    description: "GIT Token to use when checking out and commiting"
    required: true
  repo:
    description: "owner/repo (github only)"
    required: false
    default: 'current-built'
  branch:
    description: "branch to deploy to"
    required: false
    default: '${{ github.ref_name }}'
  slack-token:
    description: "Slack token for notifications"
    required: false
    default: ""
  slack-channel:
    description: "Slack channel to publish to"
    required: false
    default: ""
  is-full-site:
    description: "Whether the site being prepared is a full site repo, or not (single plugin or theme)"
    required: false
    default: "auto"
  add-mu-plugins:
    description: "Whether or not to add our MU-Plugins"
    required: false
    default: "auto"
  mu-plugins-path:
    description: "The path to use for MU-Plugins"
    required: false
    default: "mu-plugins"
  mu-plugins-branch:
    description: "The branch to use for MU-Plugins"
    required: false
    default: "develop"
  exclude-outside-collaborators:
    description: "Exclude outside collaborators from built repo"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Prepare
      if: ${{ inputs.slack-token != '' }}
      uses: saucal/action-slack-notification@v1
      with:
        token: ${{ inputs.slack-token }}
        channel: ${{ inputs.slack-channel }}
        heading: ${{ github.workflow }}
        action-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        status: 'Preparing :loading:'
        commit-repo: ${{ github.repository }}
        commit-branch: ${{ github.ref_name }}
        commit-author: ${{ github.triggering_actor }}
        commit-message: "..."

    - name: Ensure Repo Exists
      if: ${{ inputs.repo == 'current-built' }}
      id: repo-check
      uses: saucal/action-maybe-create-repo@v1
      with:
        token: ${{ inputs.git-token }}
        exclude-outside-collaborators: ${{ inputs.exclude-outside-collaborators }}

    - name: Define repo to use
      id: repo-load
      shell: bash
      run: |
        if [ "${{ inputs.repo }}" == "current-built" ]; then
          echo "repo=${{ steps.repo-check.outputs.repo }}" >> $GITHUB_OUTPUT
        else
          echo "repo=${{ inputs.repo }}" >> $GITHUB_OUTPUT
        fi

    - name: Checkout
      id: 'checkout'
      uses: saucal/action-checkout-extended@v2
      with:
        path: ${{ inputs.source }}
        token: ${{ inputs.git-token }}

    - name: Define repo to use
      id: repo-is-full
      shell: bash
      run: |
        if [ "${{ inputs.is-full-site }}" == "auto" ]; then
          if [ -d "${{ inputs.source }}/themes" ] || [ -d "${{ inputs.source }}/plugins" ]; then
            echo "state=true" >> $GITHUB_OUTPUT
          else
            echo "state=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "state=${{ inputs.is-full-site }}" >> $GITHUB_OUTPUT
        fi

    - name: Set message
      uses: saucal/action-slack-notification@v1
      with:
        commit-message: ${{ steps.checkout.outputs.message }}

    - name: Checkout previous build (if any)
      id: 'checkout-built'
      uses: saucal/action-checkout-extended@v2
      with:
        repo: "${{ steps.repo-load.outputs.repo }}"
        use: "${{ inputs.branch }}"
        path: ${{ inputs.built }}
        token: ${{ inputs.git-token }}
        use-cn: "${{ steps.checkout.outputs.cn }}"
        use-ce: "${{ steps.checkout.outputs.ce }}"
        use-an: "${{ steps.checkout.outputs.an }}"
        use-ae: "${{ steps.checkout.outputs.ae }}"
        continue-on-error: "true"

    - name: Prepare MU Plugins
      uses: saucal/action-prepare-mu-plugins@feature/platform-mu-plugins
      if: ${{ steps.repo-is-full.outputs.state == 'true' }}
      with:
        path: ${{ inputs.source }}
        git-token: ${{ inputs.git-token }}
        add-mu-plugins: ${{ inputs.add-mu-plugins }}
        mu-plugins-path: ${{ inputs.mu-plugins-path }}
        mu-branch: ${{ inputs.mu-plugins-branch }}

    - name: Prepare Composer
      uses: saucal/action-prepare-composer@v1
      if: ${{ steps.repo-is-full.outputs.state == 'true' }}
      with:
        path: ${{ inputs.source }}
        from: ${{ inputs.built }}

    - name: Set message
      uses: saucal/action-slack-notification@v1
      with:
        status: "Building :large_yellow_circle:"
