name: "Prepare Deploy"
description: "Bundle action to prepare the build process"
inputs:
  source:
    description: "Source directory"
    required: false
    default: 'source'
  built:
    description: "Previous build directory"
    required: false
    default: 'built'
  git-token:
    description: "GIT Token to use when checking out and commiting"
    required: true
  slack-token:
    description: "Slack token for notifications"
    required: true
  slack-channel:
    description: "Slack channel to publish to"
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Prepare
      uses: saucal/action-slack-notification@main
      with:
        token: ${{ inputs.slack-token }}
        channel: ${{ inputs.slack-channel }}
        status: 'Preparing :loading:'
        commit-repo: ${{ github.repository }}
        commit-branch: ${{ github.ref_name }}
        commit-author: ${{ github.triggering_actor }}
        commit-message: "..."

    - name: Ensure Repo Exists
      id: repo-check
      uses: saucal/action-maybe-create-repo@main
      with:
        token: ${{ inputs.git-token }}

    - name: Checkout
      id: 'checkout'
      uses: saucal/action-checkout-extended@main
      with:
        path: ${{ inputs.source }}
        token: ${{ inputs.git-token }}

    - name: Set message
      uses: saucal/action-slack-notification@main
      with:
        commit-message: ${{ steps.checkout.outputs.message }}

    - name: Checkout previous build (if any)
      id: 'checkout-built'
      uses: saucal/action-checkout-extended@main
      with:
        repo: "${{ steps.repo-check.outputs.repo }}"
        use: "${{ github.ref_name }}"
        path: ${{ inputs.built }}
        token: ${{ inputs.git-token }}
        use-cn: "${{ steps.checkout.outputs.cn }}"
        use-ce: "${{ steps.checkout.outputs.ce }}"
        use-an: "${{ steps.checkout.outputs.an }}"
        use-ae: "${{ steps.checkout.outputs.ae }}"

    - name: Prepare Composer
      uses: saucal/action-prepare-composer@main
      with:
        path: ${{ inputs.source }}
        from: ${{ inputs.built }}

    - name: Set message
      uses: saucal/action-slack-notification@main
      with:
        status: "Building :large_yellow_circle:"
